Refactor PoC for chat client and server
Momentous-Muses/code-jam pull request #7
Opened 2022-07-24 17:22 UTC by TobeTek

2022-07-24 19:08 UTC, ooliver1 requested changes

2022-07-24 19:08 UTC, ooliver1 commented on .pre-commit-config.yaml
> -    rev: v2.5.0
This should probably be in its own PR.

2022-07-24 19:08 UTC, ooliver1 commented on poc/events.py
> +    def from_dict(cls, data: Dict[Any, Any]):
```suggestion
    def from_dict(cls, data: Dict[str, Any]):
```
field names are always string

2022-07-24 19:08 UTC, ooliver1 commented on poc/ws_client.py
> +SIMPLE CLIENT
Why are your single-line docstrings on 3 lines, the [PEP 257](https://peps.python.org/pep-0257/) conventions say:

```py
"""single line summary"""
```

```py
"""single line summary

optional larger
description
"""
```

2022-07-24 19:08 UTC, ooliver1 commented on poc/ws_client.py
> +        self, ws_connection, producer: Awaitable, consumer: Awaitable, *args, **kwargs
Typehint `ws_connection` and use a generic on `Awaitable` to denote the return types. Also why is `*args, **kwargs` added when never used?

2022-07-24 20:15 UTC, TobeTek commented on .pre-commit-config.yaml
> -    rev: v2.5.0
Came up as I was fixing some pre-commit errors. 
I'll checkout to the last version of the `.pre-commit-config.yaml` and we should be good?

2022-07-24 23:26 UTC, TobeTek commented on poc/ws_client.py
> +SIMPLE CLIENT
They're serving as headers/comments here, not necessarily docstrings.

2022-07-25 12:53 UTC, ooliver1 requested changes

2022-07-25 12:53 UTC, ooliver1 commented on poc/README.md
> +# To Run
markdown should not include more than one level 1 header
```suggestion
## To Run
```

2022-07-25 12:53 UTC, ooliver1 commented on poc/README.md
> + - Ready to go 🚀
```suggestion
Uncomment as appropriate to run the CLI or GUI chat client

```

2022-07-25 12:53 UTC, ooliver1 commented on poc/events.py
> +    def to_dict(self):
Include an explicit return type
```suggestion
    def to_dict(self) -> Dict[str, Any]:
```

2022-07-25 12:53 UTC, ooliver1 commented on poc/ws_client.py
> +SIMPLE CLIENT
But still, why do they need 3 entire lines for a one line comment?

2022-07-25 18:04 UTC, c-gaskell commented
I think it would be much cleaner to have separate submodules for client and server... ie their own folders with __init__.py etc. This means if multiple files are needed they're kept separate

2022-07-25 21:20 UTC, TobeTek commented
> 

The final implementation would have a far better code structure. There are already existing folders/modules for `client` and `server`.

2022-07-26 11:40 UTC, ooliver1 approved these changes
Good enough for me as a first implementation

2022-07-26 17:17 UTC, merged