Add threaded websocket client
Momentous-Muses/code-jam pull request #8
Opened 2022-07-24 21:48 UTC by Numerlor

Adds a thread safe websocket client that can dispatch messages to multiple subscribed consumers through queues. Example usage here https://github.com/Momentous-Muses/code-jam/blob/ed39be036b2e9d2584757a5a73c02ec5cff4ab07/client/websocket_client/client.py#L51-L61

New message classes are created as Message subclasses, e.g.
```py
@dataclass
class CustomMessage(websocket_client.Message):
    channel = "test_channel"
    type = "test_type"

    @classmethod
    def from_json_dict(cls, json_):
        return cls_created_from_json

    def to_json(self) -> str:
        return json.dumps(as_dict(self))
```
after the Message subclass is created, when a message with the given type is received on a channel, the class is created from the received json and sent to all queues on the given channel.

The uassage I have in mind is that the tkinter client will create the dispatcher, keep it around and for each queue it subscribes for (each channel will represent a different, separate part of the communication), it'll poll it with a function scheduled with `app.after`

2022-07-25 00:11 UTC, c-gaskell approved these changes

2022-07-25 12:56 UTC, ooliver1 requested changes
Otherwise, looks good!

2022-07-25 12:56 UTC, ooliver1 commented on client/websocket_client/__init__.py
> +__all__ = ["Message", "ResultEvent", "UNINITIALIZED", "WebsocketMessageDispatcher"]
```suggestion
__all__ = ("Message", "ResultEvent", "UNINITIALIZED", "WebsocketMessageDispatcher")
```
`__all__` does not need mutation

2022-07-26 17:21 UTC, c-gaskell commented
There's merge conflicts for poetry.lock - i'm not entirely sure how this file works, does anyone else know how this conflict should be resolved?

2022-07-26 17:27 UTC, Numerlor commented
for lock file conflicts, it just has to be generated again; I've resolved it and brought the branch up to date with main

2022-07-26 17:27 UTC, c-gaskell commented
Just waiting for the review from @ooliver1 before I can merge as he requested changes, once that's done I'm good to merge

2022-07-26 17:30 UTC, ooliver1 approved these changes

2022-07-26 17:30 UTC, merged